### ISSUE TITLE
What on earth is going on?

### ISSUE THREAD

**Issue by Deminetix** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#1]
Guys, we had our deeplink integration with you working perfectly for about a month, we pushed to production. Our product works very closely with branch functionality to support our use-cases. If branch breaks, our stack falls over on its face.

* I went to make a new build last week only to find the plugin is broken, i went to the repo and immediately see a commit `ripped out cordova implementation`
* eventually figured out it was moved to this repo, please email your customers?
* switched to new repo, looks ok. Deploy to device, links aren't opening our app, they go directly to the web fallback url
* Log into branch dashboard, half our settings for test/live are gone or screwed (bad migrations maybe?)
* Our schema url was `appname://test://` instead of `appname://` and the urls were all malformed/missing too.

I still haven't quite been able to get our app to open after clicking a link that has been generated. I'm wondering if this functionality even still works?

**Comment by aaustin** [comment]
@Deminetix I'm so sorry about the migration to this repo. I take full responsibility for this. We had so many people confused about how to use the previous web library that it was getting out of control. I drastically over-reacted and asked to split out the repositories. I'm really sorry about this.

In terms of the links, we didn't adjust any settings at all on the apps. The only change over the last week was to the local repository. I'm unsure how your dashboard settings could have degraded, but I'd like to get this link opening functionality restored for you. I'm looking into the settings now and will reply soon once I know more.

**Comment by aaustin** [comment]
Ash - I just took a look at your dashboard. It seems your links are configured to use our default URI scheme + host which is:
glow://open?link_click_id=1234

Have you added the 'open' host to your Manifest on Android? This won't matter on iOS

**Comment by Deminetix** [comment]
Hi Alex,

I managed to get it going again, and I'm not 100% sure what was going on. It's all quite a dance to set up.

Splitting out the repo for cordova is definitely a good idea, I just didn't see it coming. 

When I get some time I'd like to make a few PRs that will help others with setup in the future. 

The recommended practice with Cordova is to omit the platforms directory from your repo, so manually changing native code wasn't feasible for us and goes against the point of Cordova anyway. We use a couple of hooks to edit manifests and plists etc

The other time consuming task is the JavaScript interface and handling lifecycle events differently when the user is logged in or not. I assume a lot of your users will need to tackle this so I'll share our angular service at some point too.

Thanks for getting back me so quickly

**Comment by aaustin** [comment]
I'm so glad you did.. You suggestions sound very useful - we'd love to review some pull requests if you modified the main repos.

Again, I'm really sorry we screwed you over here. I take full responsibility since I issued the command without thinking through the consequences. I just saw your other note which we'll dig into. Please let me know if I can help in any way.
