### ISSUE TITLE
Error onNewIntent on Android while application is running

### ISSUE THREAD

**Issue by Morathil** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#101]
We are experiencing problems when using local notification plugin (http://github.com/katzer/cordova-plugin-local-notifications) in combination with Branch. BranchSDK is throwing the following error when a new Intent is created (e.g. click on push notification) while the application is already running:

`
 FATAL EXCEPTION: main
  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null object reference
      at io.branch.BranchSDK$SessionListener.onInitFinished(BranchSDK.java:806)
      at io.branch.referral.Branch.initUserSessionInternal(Branch.java:1062)
      at io.branch.referral.Branch.initSession(Branch.java:742)
      at io.branch.referral.Branch.initSession(Branch.java:816)
      at io.branch.BranchSDK.initSession(BranchSDK.java:257)
      at io.branch.BranchSDK.onNewIntent(BranchSDK.java:58)
      at org.apache.cordova.PluginManager.onNewIntent(PluginManager.java:328)
`

We assume that this happens because `_callbackContext` of `SessionListener` is set to null on `onNewIntent` and `onInitFinished` is called from  `initUserSessionInternal` (Branch.java line 1048) without checking if `_callbackContext` is set.
Actually there is a check for `callback` in `initUserSessionInternal` but in this case `callback` is an instance of `SessionListener` which is not `null` but internally has no `_callbackContext` set.

Can somebody with more Android experience have a look into this issue, please? :sweat_smile:

**Comment by harshabonthu** [comment]
We don't use local notifications plugin and still see the same error. More details here -> http://crashes.to/s/18076f3717b

**Comment by renesansz** [comment]
Hi @Morathil @harshabonthu ,
Just have submitted a pull request #103 . Hopefully this will resolve the issue.

**Comment by Morathil** [comment]
Hey @renesansz 

Pull request #103 fixed the issue for us.
Thanks for the fast fix!

**Comment by renesansz** [comment]
cool! glad to hear that it fixes the issue. :+1:
