### ISSUE TITLE
SessionParams only read from defaults when already set

### ISSUE THREAD

**Issue by TheMarshal99** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#107]
[Link](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/ff645365bb697d2c49cccc309c5ac9e6d4278f0d/src/ios/dependencies/Branch-SDK/BNCPreferenceHelper.m#L355)

**Comment by TheMarshal99** [comment]
This of course means that if the _sessionParams object had ever changed, it would always get overwritten with whatever was in the defaults.

**Comment by aaustin** [comment]
Resolved in main repo
