### ISSUE TITLE
Android builds broken... again

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#112]
This is getting pretty old.  It seems the latest build in NPM is broken for Android again.  This happens like once a month.

:compileReleaseJavaWithJavac/project/src/io/branch/BranchSDK.java:1235: error: method showShareSheet in class BranchSDK cannot be applied to given types;
                        showShareSheet(this.args.getInt(0), this.args.getJSONObject(1), this.args.getJSONObject(2));
                        ^
  required: int,JSONObject,JSONObject,String
  found: int,JSONObject,JSONObject
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by aaustin** [comment]
Hmm - it seems that the interface was changed without support for past implementations. Let me put in a fix for this. Apologies!

**Comment by aaustin** [comment]
Apologies for this. I added support for past implementations and this should be resolved now. Really sorry again.
