### ISSUE TITLE
Crash on iOS when opening link when the app is in the background

### ISSUE THREAD

**Issue by chancezeus** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#116]
I have installed the branch sdk and added a custom subdomain in the dashboard and config. When the app is not running, clicking on a link it opens up the app nicely and performs the requested action. However when the app is already running it crashes the moment a link gets clicked. After some digging I found that the problem probably is the following:
In src/ios/BranchSDK.m on line 541 is the following line:
```NSString *urlString = [notification.object absoluteString];```
This probably means that the notification.object you expect is an NSUrl, however the crash notes that the object is an __NSCFString (internal type of NSString) which doesn't have an absoluteString method/property.

**Comment by chancezeus** [comment]
As a quick fix this seems to work:
Replace:
```NSString *urlString = [notification.object absoluteString];```
With:
```
    NSString *urlString;

    if ([notification.object respondsToSelector:@selector(absoluteString:)]) {
        urlString = [notification.object absoluteString];
    } else {
        urlString = notification.object;
    }
```

The crash disappeared, but the requested action does not get handled...

**Comment by renesansz** [comment]
Hey @chancezeus ,
Thanks for providing a quick fix for the issue, I'll look more in to it on why the requested action does not get handled.

**Comment by chancezeus** [comment]
I have changed some of the JS code and I've got it to work using this quick fix. I don't know why or how actually, it seemed like it had something to do with not being able to call the NonBranchLinkHandler (which I didn't need, so didn't define)...

**Comment by renesansz** [comment]
Good to hear that you were able to fix the issue by providing a quick fix & updated your JS code.
May I know how you did it also in JS? It might be useful for others who might have this kind of problem also.
Just have submitted #117 with your quick-fix.

**Comment by aaustin** [comment]
This has been merged. Closing out!
