### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by cktg** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#121]
I am getting the following error when running "ionic run android" test...

Uncaught ReferenceError: Promise is not defined, http://192.168.1.73:8100/plugins/io.branch.sdk/www/branch.js, Line: 26

How do I fix it?

**Comment by renesansz** [comment]
@cktg ,
Can you give me the build details of your app? (eg: plugin versions, Cordova version, etc.)

Thanks

**Comment by cktg** [comment]
@renesansz , 
Sorry for the late reply. For some unknown reasons, es6-promise-plugin was not included during installation. The error is gone after reinstalling branch. 

Thanks.
