### ISSUE TITLE
Stage parameter not passed when doing  showShareSheet

### ISSUE THREAD

**Issue by barocsi** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#122]
```
 branchUniversalObj.showShareSheet({
                                                           feature: "share",
                                                           stage: stage
                                                         },
                                                         {},
                                                         sharetext
                       );
```
In the dashboard the created links stage parameter is null.
And by the way, what happened to the tags parameter?
Using Cordova/Ionic 
Branch SDK 2.0.3

**Comment by barocsi** [comment]
And by th way, where are the tags parameters?

**Comment by renesansz** [comment]
@barocsi ,
Please elaborate your question? Thanks

**Comment by aaustin** [comment]
Hey @barocsi - I believe this is fixed in the latest live version. I can't seem to reproduce.

**Comment by barocsi** [comment]
Hello, thanks for the reply.
Reproduce:
When I create a branch link through the above, for example 
```javascript
branchUniversalObj.showShareSheet({
                                                           feature: "sharex",
                                                           stage: "testx"
                                                         },
                                                         {},
                                                         somesharetext
                       );
```
Then open the dashboard events view, I can see the link and all its properties, but stage is null.
```
Alias: null
Branch Identity ID: xxx
Campaign: null
Channel: Facebook
Creation Source: SDK
Time: 2016. 04. 26. 11:58:29
Data: //{ stripped out }
Domain: bnc.lt
Feature: sharex
id: 253447038765686666
Link ID: 253447038765686666
Stage: null
Tags: []
URL: bnc.lt/F5kk/kE9Hpp9WSs
```
**Stage: null**

I have also mentioned that there is no reference in the new doc to the Tags property.

Also its a question, if my user is from a campaign, installs the app will the branch fill in the campaign as it does with the channel automatically?

Thanks.

**Comment by barocsi** [comment]
Same with  
```
branchUniversalObj.generateShortUrl({
                                                           feature: "invite",
                                                           channel: "Facebook",
                                                           stage: stage
                                                         }, {}).then(function (res) {.....
```
The visible parameters on branch desktop are only the feature: invite.

**Comment by aaustin** [comment]
I found the issue @barocsi https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/120/commits/c22fbb9e66e2632665a8e6bf7a1151ec5a6942ce Added to my big PR.

**Comment by aaustin** [comment]
This should be resolved now.

**Comment by barocsi** [comment]
Have updated to the master, but stage parameter not seem to be passed when using sharesheet.
I have removed and readded the plugin as well.

**Comment by renesansz** [comment]
Hi @barocsi ,
This issue is both for Android & iOS? I'll take a look at the issue for this.

**Comment by barocsi** [comment]
For me this happens only on Andriod. 
On iOS the Stage parameter is passed through.
