### ISSUE TITLE
Troubleshooting when not opening yourapp:// in app

### ISSUE THREAD

**Issue by barocsi** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#129]
I'm not sure yet, however tests indicating that whitelist plugin might cause some problems. Please look it over and add stuff accordingly.
According to this https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/the-whitelist-system.md 
and
http://stackoverflow.com/questions/34257097/using-handleopenurl-with-custom-url-scheme-in-cordova/34281420#34281420
and
https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/whitelist-matrix.md

However for me whitelist plugin is installed, grademill is not whitelisted in allow-intent and the app opens in safari the link first and starts downloading the page. Then after a while it opens in in my app, however there are 2-3 seconds needs to be passed before it happens.

On Android the phenomena is the same, but without any delay.

**Comment by aaustin** [comment]
Mind sharing what code you added to get yours working? I can update the scripts or readme appropriately.

**Comment by barocsi** [comment]
**_Disclaimer: The following applies only to iOS 8.4 vs 9.2 and above I can only do arbitrary empirical testing since I am not sure what's really going on in this plugin._**

The universal link validator for my app and bundle shows my app in the very long list. It even shows the very long list if I filter it for my app and bundle id. Is this intended behavior?
By the way, the four character id beforehand of the link is not ALL CAPS however in the xml you can see its F5KK all caps. 

My custom links domain on the Dashboard -> Link settings bottom page shows `bnc.lt`

I have been upgrading from legacy 1.8 Branch SDK with `applinks:bnc.lt` defined on Capabilities/Associated Domains tab.

### First test, iOS 8.4:

I have tested it on iOS 8.4, standard settings
config.xml does not have anything extra definitions other than the
```xml
  <branch-config>
    <ios-team-id value="4VBHL6K778"/>
    <host name="bnc.lt" scheme="https"/>
    <android-prefix value="F5KK"/>
    <host name="bnc.lt" scheme="https"/>
  </branch-config>
```
entitlements are enabled 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>applinks:bnc.lt</string>
</array>
</plist>
```
**Result:**
And it worked like:
- get share link
- click on it from mail / or paste it in safari
- opens in safari (if clicked from mail)
- safari redirects to my app

Seems URI scheme based routing worked.

### Second test, iOS 9.2, settings identical to above (simulator).
Same steps above did not produce any redirect to my app.
Moreover, on safari it redirected to my deepview page, where I clicked on Get The app, and safari popped out an error:

> Cannot Open Page
> Safari cannot open the page because the address is invalid.

Interestingly, this some times happens to iOS 8.4 as well, but more randomly. 
Sometimes when I open from within Safari Facebook page it works and redirects.

**Comment by barocsi** [comment]
According to legacy bnc.lt links should the path be defined differently?
According to this 
https://branch.io/resources/universal-links/
"paths": [ "*", "/" ]

**Comment by barocsi** [comment]
According to this
https://forums.developer.apple.com/thread/44526

On simulator, Universal Links might not work.

I need to clarify this by testing on real 9.2 device.

**Comment by barocsi** [comment]
Tried in 9.3.1 live device and it does not opening up the app when clicked on the branch link from email, or facebook app.

bump.

**Comment by renesansz** [comment]
Hi @barocsi ,
We're still trying to investigate the issue, however we'll look in to the findings you've reported and hopefully it would help us resolve this issue.

**Comment by barocsi** [comment]
Any ideas why url scheme based deep linking wont work above iOS 8.4?

**Comment by renesansz** [comment]
In iOS 9 there's this another security permission that needs to be enabled for the app.
See this stackoverflow [question](http://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme)

**Comment by barocsi** [comment]
Tried all. I will try in Ad Hoc release mode.

**Comment by aaustin** [comment]
This seems like the same issue at #132 - can you try testing from a Universal Link supported app? https://dev.branch.io/getting-started/universal-app-links/support/ios/#appsbrowsers-that-support-universal-links

**Comment by barocsi** [comment]
# Possible resolution:

## Test urlscheme typed in safari

For testing why URLScheme works only on iOS8.4, I have just typed in my iOS 9.3 device (and in simulator) Safari the app url I wanted to work in safari like myapp:// and it popped up the question whether I wanted to open it in my app. At least it works...!

## Link tests

Created a marketing link for grademill:// sitting on [https://bnc.lt/xxyy](https://bnc.lt/xxyy)

### Test bnc.lt link in iOS9.3

However when I do enter https://bnc.lt/xxyy link (universal links not enabled) it does not do the same. It never wants to open any app. 

### Test bnc.lt link in iOS8.4

Works.

## Server responses

What is your server side logic? Nor in the source nor in any redirection could I found a trace on branc.io pages that it has any intent to open it in my app.

## Plain server test for grademill:// location change in JS

> As of iOS 9.2, the dialog Open in "mycoolapp"? no longer blocks JS, so if you have a short timeout that opens the app store, the user will be taken to the store before they have a chance to see and answer the dialog. See below for available solutions.
from 
https://github.com/EddyVerbruggen/Custom-URL-scheme

Following that I have simply added a code to an arbitrary domain https://foo.com/schemetest.html
```html
<html>
<head>
</head>
<body>
Scheme Test
<script>
// self executing function here
(function() {
location.href = 'grademill://'
})();
</script>
</body>
</html>
```

Called this uri from Safari and it popped up the popup asking if I wanted to open it in my app. Ok.

## Inspection

I started to inspect bnc.lt behavior when opening from mobile agent simulation and used network inspection to see what kind of requests go:

### Simulating request by Android agent KitKat

When simulating android the response was a `307`
```
Location: intent://open?link_click_id=218298976313607721#Intent;scheme=grademill;package=com.xopyo.grademill;S.browser_fallback_url=https%3A%2F%2Fbnc.lt%2Fd%2F71EgKijQXs%2Fchrome_deepview%3F_branch_match_id%3D218298976313607721;end
```
### Simulating request with iOS Simulator 8.4

When simulating iOS8.4 safari and opening the same link, there was no 307, but something I expected from above:

```html
<script type="text/javascript">window.onload = function() {document.getElementById("l").src ="grademill://open?link_click_id=253842431403329984";};var img = document.createElement("img"); img.src = "/d/JIrWaISRXs/deepview_serve?app_id=218298651888341381"; document.body.appendChild(img);</script>
```

### Simulating request with iOS Simulator 9.3

When simulating in iOS9.3 Safari, and opening the same link the only javascript I have found was:
```html
<script type="text/javascript">var img = document.createElement("img"); img.src = "/d/qqvcUigSXs/deepview_serve?app_id=218298651888341381"; document.body.appendChild(img);</script>
```
I did not see any 307s nor location tags in the response. Nor any specific response header value.

Therefore I simply did insert the code from 8.4 response to my simple webserver schemetest.html and opened with iOS 9.3 simulator, so https://foo.com/schemetest.html showed

```html
<html><head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:700,300" rel="stylesheet" type="text/css">
	<style>
		body {
			margin: 0;
			word-wrap: break-word;
		}
		/* ============ Portrait ============ */
		.main-image {
			width: 100%;
			height: 250px;
			height: 75vw;
			background-image: url("");
			background-size: cover;
			background-position:top center;
		}
		#content-container {
			box-sizing:border-box;
			padding: 24px;
			margin:0 24px 0 24px;
			background-color: #ffffff;
		}
		.app-title {
			font-size: 14px;
			padding-bottom: 11px;
			text-transform: uppercase;
		}
		.card-title {
			font-size: 33px;
			line-height: 36px;
		}
		.app-content {
			padding-top: 10px;
			padding-bottom:100px;
			font-size: 20px;
		}
		.input-wrapper {
			position: fixed;
			bottom: 0;
			left: 0;
			width:100%;
			height:110px;
			background-color: white;
			-webkit-box-shadow: 0px -20px 20px -8px rgba(255,255,255,1);
			-moz-box-shadow: 0px -20px 20px -8px rgba(255,255,255,1);
			box-shadow: 0px -20px 20px -8px rgba(255,255,255,1);
		}
		.input-container {
			width:100%;
			padding:0 24px;
			text-align:center;
			-webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
			box-sizing: border-box;
		}
		.form-get-the-app {
			text-align:center;
			padding-top: 10px;
			border-top: 2px solid #CECECE;
		}
		.form-get-the-app > input {
			margin-right: 10px;
			padding-top: 10px;
			padding-bottom: 10px;
			background-color: #FFFFFF;
			border: 1px solid #979797;
			border-radius: 2px;
			font-size: 60px;
			color: #CECECE;
			line-height: 24px;
			padding-left: 20px;
		}
		.input-label {
			padding-bottom: 4px;
			font-size: 13px;
			padding-left: 10px;
			padding-right: 10px;
			overflow: hidden;
			word-wrap: break-word;
			padding-top: 4px;
			text-align: center;
		}
		.app-icon {
			content:" ";
			float:left;
			display:inline-block;
			width:62px;
			height: 62px;
			line-height: 62px;
			background-size:100% auto;
			background-image:url();
		}
		.cta-button {
			display:block;
			height: 62px;
			line-height:62px;
			background-color: #444444;
			border-radius: 2px;
			font-size: 20px;
			padding:0 20px;
			margin-left:70px;
			color: #FFFFFF;
			text-align: center;
			text-decoration: none;
		}
		/* No data (portrait) */
		@media only screen and (orientation: portrait) {
			.card--no-data .main-image {
				background-image: url("http://s3-us-west-1.amazonaws.com/branch-assets/b_stripes-small.png");
				background-size: auto;
				background-position: top center;
				background-repeat: repeat;
				height: 190px;
			}
			.card--no-data > .app-icon {
				position: absolute;
				top: 160px;
				left: 34px;
			}
			.card--no-data #content-container {
				margin-top:20px;
			}
		}
		@media screen /* >= iPhone 5 */
		and (min-device-width: 321px) {
			.input-label {
				font-size: 14px;
			}
		}
		@media only screen /* >= iPhone 6 */
		and (min-device-width: 375px)
		and (orientation: portrait) {
			.main-image {
				height:300px;
				height: 80vw;
			}
			.app-content {
				padding-bottom:120px;
			}
			.input-wrapper {
				height:115px;
			}
		}
		@media only screen /* >= iPhone 6+ */
		and (min-device-width: 414px)
		and (orientation: portrait) {
			.main-image {
				height:390px;
				height: 95vw;
			}
		}
		/* ============ Landscape ============ */
		@media only screen and (orientation: landscape){
			.main-image {
				position:fixed;
				height:100%;
				height:100vh;
				width: 50%;
			}
			.input-wrapper {
				right:0;
				left:auto;
				width:50%;
			}
			#content-container {
				float:left;
				width:50%;
				margin-left:50%;
			}
			.input-wrapper {
				height:108px;
			}
			.app-content {
				padding-bottom:110px;
			}
			.form-get-the-app {
				padding-top:8px;
			}
			.input-container {
				left: 50%;
			}
			.cta-button {
				height: 44px;
				line-height: 44px;
				padding:0 5px;
				margin-left:50px;
			}
			.app-icon {
				width: 44px;
				height: 44px;
			}
			/* No data (landscape) */
			.card--no-data .main-image {
				height: 100%;
			}
			.card--no-data > .app-icon {
				display:none;
			}
			.card--no-data #content-container {
				margin-top:0;
			}
		}
		@media only screen /* >= iPhone 6 */
		and (min-device-width: 645px)
		and (orientation: landscape) {
			.form-get-the-app {
				padding-top:8px;
			}
			.cta-button {
				height: 62px;
				line-height: 62px;
				padding:0 20px;
				margin-left:70px;
			}
			.app-icon {
				width: 62px;
				height: 62px;
				top:-2px;
			}
		}
		/* Reusables */
		.text-bold {
			font-family: "Open Sans", Helvetica, serif;
			font-weight: 700
		}
		.text-light {
			font-family: "Open Sans", Helvetica, serif;
			font-weight: 300;
		}
		.cta-button--no-app-icon {
			margin-left:0;
		}

	</style>
</head>
<body>
	<div class="card card--no-data center">
		<div class="main-image"></div>
		<div class="app-icon">&nbsp;</div>
		<div id="content-container">
			<div class="app-title text-bold">Grademill - awesome decision making in real-time!</div>
			<div class="card-title text-light"></div>
			<div class="app-content text-light"></div>
		</div>
		<div class="input-wrapper">
			<div class="input-container">
				<div class="input-label text-light">See this content immediately after install</div>
				<form class="form-get-the-app">
					
					<a href="https://bnc.lt/d/eVkRAOHTXs/viewapp" class="cta-button text-light cta-button--no-app-icon cta-button--no-app-icon">Open The App</a>
				</form>
			</div>
		</div>
	</div>
<script type="text/javascript">window.onload = function() {document.getElementById("l").src ="grademill://open?link_click_id=253842431403329984";};var img = document.createElement("img"); img.src = "/d/eVkRAOHTXs/deepview_serve?app_id=218298651888341381"; document.body.appendChild(img);</script><img src="/d/eVkRAOHTXs/deepview_serve?app_id=218298651888341381"><iframe id="l" width="1" height="1" style="visibility:hidden" src="grademill://open?link_click_id=253842431403329984"></iframe>
</body></html>
```
**And I simply requested this url from iOS9.3 device and it DOES NOT WORK returning an error:.**
`Failed to load resource: unsupported URL`

## Conclusion

So I understand the change from 8.4 to 9.3 within the source code because you wanted to switch to Universal Links, but I have unchecked the universal links box and still, there is no indication of using urlscheme fallback from within your app (in case universal link is not working) through javascript.

Since Universal Link is limited, and for some reason it is not working for me, URI Schemes would do. But apparently for the deepviews do not include such.

Reading this exact reference of the problem
http://stackoverflow.com/questions/31891777/ios-9-safari-iframe-src-with-custom-url-scheme-not-working

Indicates replacing URL Scheme fallback should be done by replacing iframe solution to the above mentioned `window.location = 'custom-protocol://my-app' type.`

Which apparently have some fallbacks:

> That's correct. That's why the iframe trick on iOS 7 and 8 was so nice. Only set window.location='custom-protocol://'; if you're okay with the error message or if you are fairly certain the user has your app. – st.derrick Oct 1 '15 at 16:47

So it might be clarified now, why URLScheme was not working as a fallback if Universal Links are turned off. I am still not sure what was your intended mechanism, but either way it is unclear and must be considered.

**Comment by aaustin** [comment]
Thanks for all of this work testing. You've basically gone through everything we have compiling all of the edge cases on iOS over the last few iOS versions. I'll reply to your more up-to-date comment in #132

**Comment by dtruel** [comment]
Try using a custom domain or subdomain instead of bnc.lt.  We couldn't get it to work in development mode because there was an issue with the development account.

I would also recommend reading up on how deep links work apart from branch.  Also once add configurations to your config.xml try removing and adding back ios.   You can check bnc.lt/apple-app-site-association and make sure that your app is listed there - if it's not, or if the path is incorrect, it won't work.
