### ISSUE TITLE
setIdentity(object) returns weird data, undocumented

### ISSUE THREAD

**Issue by barocsi** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#138]
Hello,

exactly, what kind of data should setIdentity function return? Seems that it stored something in relation to the first link generation (?)
I get this:
```
$identity_id: "252785992883276315"
$og_app_id: "1757534501136057"
$og_description: "***STRIPPED, BUT SOME OLD SHARING ITEMS DESCRIPTION ***"
$og_image_url: "***STRIPPED, BUT SOME OLD SHARING ITEMS IMAGE***"
$og_title: "***STRIPPED, BUT SOME OLD SHARING ITEMS TITLE***?"
$one_time_use: false
$state: "main.tabs.single"
$stateParams: "{"postId":"571c1d4ba5800ace7c9e4558"}"
~channel: "mobile"
~creation_source: 2
~feature: "share"
~id: "252787154801969859"
~stage: "post"
```

**Comment by renesansz** [comment]
Hi @barocsi ,
It sets the identity of the user, this could be an email address, UUID, or Facebook ID.
It returns to you the generated data of the identity of the user, from the Branch.IO documentation:
* $identity_id - Is the server-generated ID of the user identity, stored in `sessionStorage`.
* ~feature - Is the type of the generated identity
* ~channel - The device type used

I don't have an idea for the other returned parameters, but somehow those data are somewhat needed for the user identity.

**Comment by barocsi** [comment]
Its then some sort of initial data, however seems to be weird and unexpected.

**Comment by renesansz** [comment]
Yes, I think so. I wasn't able to really work with the SDK for the native library.

**Comment by aaustin** [comment]
Hey @barocsi - I can answer this one. In the setIdentity call, we return the first link that a user clicked to refer them into an app. We consider this to be the original referring link and wanted to make the data available to use in product.

**Comment by barocsi** [comment]
That was my tip, thanks a lot.
