### ISSUE TITLE
setDebug has no effect

### ISSUE THREAD

**Issue by ripcurlx** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#14]
Hi!

I'm trying to activate the debug mode by setting branch.setDebug before branch.init, but it doesn't make any difference and only tracks a open instead of an install. I've stepped into it with the debugger and the debug flag is set properly. Unfortunately the compressed google closure code isn't very easy to debug.
It seems to be as if an install tracking is sent to branch backend:
https://api.branch.io/v1/install
request:
```
sdk:	cordova1.7.0
hardware_id:	[HARDWARE_ID]
is_hardware_id_real:	true
app_version:	[APP VERSION]
brand:	Apple
model:	iPad4,1
os:	iOS
uri_scheme:	[URI_SCHEME]
os_version:	8.4
screen_width:	2048
screen_height:	1536
is_referrable:	1
branch_key:	[BRANCH_KEY]
```
response:
```json
{
	"session_id": "[SESSION_ID]",
	"identity_id": "[IDENTITIY_ID]",
	"device_fingerprint_id": "[DEVICE_FINGERPRINT_ID]",
	"browser_fingerprint_id": null,
	"link": "https://bnc.lt/j/JVz0WDSvum",
	"identity": "1020",
	"data": "{\"$desktop_url\":\"http://www.desktopurl.com\",\"$marketing_title\":\"Test Install\",\"$one_time_use\":false,\"~campaign\":\"install\",\"~channel\":\"Landingpage\",\"~creation_source\":\"Dashboard\",\"~feature\":\"marketing\",\"~id\":\"176980187282456102\",\"+match_guaranteed\":true,\"+click_timestamp\":1443435811,\"+is_first_session\":false,\"+clicked_branch_link\":true}"
}
```
Also the trick to add a debug device for a cordova based app somehow doesn't work. Is there a way to do this manually, besides the four finger press trick?

Best

Christoph

**Comment by Kirkkt** [comment]
Indeed, reading the code https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/src/6_branch.js#L249 setDebug doesn't seem to actually do anything for Cordova.

We are low on man power at this moment so I will list this as low-pri. 

Thanks for reporting the bug! I will let you know when I can get on with it.

**Comment by ripcurlx** [comment]
Thanks for looking into it @Kirkkt! I think it only doesn't work on iOS. On Android it is passed through to the ```getUniqueID``` call, where a random ```androidID``` is generated every time. Still the four finger trick only works with the native SDKs.

**Comment by ripcurlx** [comment]
Just had time to check the Android part of it. It's the same problem as with the iOS version.

**Comment by edanchenkov** [comment]
That's what we really need ASAP !

**Comment by jsaleigh** [comment]
Hi @ripcurlx, sorry this took so long to get fixed, but the setDebug code should be working for you now on iOS and Android.  Please let me know if you see any problems using it now.

**Comment by aaustin** [comment]
This was resolved in recent version.
