### ISSUE TITLE
Branch not ready on deviceready event

### ISSUE THREAD

**Issue by rphansen91** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#16]
After a lot of struggles with the SDK and seemingly random responses / no response from the branch.init() method I integrated [Weiner](http://people.apache.org/~pmuellr/weinre/) in order to view the network requests and Local Storage of the device.

Sometimes when logging the branch object the values are populated and methods are in place. However much of the time the branch object logs empty with solely the __proto__ property and the init function is undefined.

As I am using branch asynchronously this blocks the load of my app as other components depend on this data. How can I ensure that branch is ready everytime the user opens the app?

**Comment by rphansen91** [comment]
Here is the gist of the branch initialization code
    
    var nativeAppTypeProvider = {}
    nativeAppTypeProvider.AndroidDeviceReady = function () {		
		if (branch && typeof branch.init == "function") {
			branch.init(ENVIRONMENT.branchKey, function(err, data) {
				alert(JSON.stringify(data))
				alert(JSON.stringify(err))
				branch.first(function (firstErr, firstData) {
					alert(JSON.stringify(firstErr))
					alert(JSON.stringify(firstData))
					branch.close()
				})
	      	})
		} else {
			alert("Branch not initialized")
		}
	}

    document.addEventListener('deviceready', nativeAppTypeProvider.AndroidDeviceReady, false)

On the first open/load of the app branch initializes and the init and first callbacks fire successfully, however on subsequent attempts after a hard close of the app `branch` is typeof Object however branch.init is undefined within the scope of the `nativeAppTypeProvider.AndroidDeviceReady` function after the `deviceready` event

**Comment by requested** [comment]
Any progress with this? I'm experiencing the same issue right now.

**Comment by aaustin** [comment]
We're about to dig in and spend substantial time upgrading this repo. Give us a couple days.

**Comment by jsaleigh** [comment]
Hi @rphansen91, we recently made a change which may help with the issue you're seeing, both on the master branch and tagged with v1.7.1

If you are still seeing the issue with this new build, please let me know.

**Comment by aaustin** [comment]
Closing since it was addressed in earlier version
