### ISSUE TITLE
Cordova crashing on android as soon as plugin is installed

### ISSUE THREAD

**Issue by dangreenisrael** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#19]
As soon as I installed the plugin on my android device (Nexus 5 - fully updated) I started having random crashes with the notice 
```The connection to the server was unsuccessful. (file ///android_asset/www/index.html)```

Uninstalling the plugin fixes the problem immediately.

This also happens on the first gen moto g, but not on some newer devices.

The bug can be intermittent, but opening and closing the app enough times will reproduce it.

**Comment by aaustin** [comment]
@dangreenisrael Really sorry to hear this but it's the first time we have. Is there any additional info you can offer around the crash? As an example, is it happening on app open? or on app close? Do you get any other info in the crash?

**Comment by dangreenisrael** [comment]
The worst crash is happening on app open - it doesn't even begin to launch the app.

Some googling let me to believe that it was a problem with a 3rd party plugin - and as branch was the only new plugin I was using I removed it and all was fixed.  I reinstalled it started causing the problem again.

Here is my list of cordova plugins

```com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-datepicker 0.8.5 "DatePicker"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
nl.x-services.plugins.socialsharing 4.3.12 "SocialSharing"
org.apache.cordova.dialogs 0.2.11 "Notification"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
phonegap-plugin-push 1.3.0 "PushPlugin"
```

I have an android crash report if you want it - JS is irrelevant because it didn't even load index.html.

![android problem with branch](https://cloud.githubusercontent.com/assets/4509692/10756576/a1134a22-7cad-11e5-837f-fb83fbeb68d7.jpg)

**Comment by dangreenisrael** [comment]
I should say though, that when it worked - it worked really well.

I'd love to be able to keep using Branch, I think its a great product

**Comment by jsaleigh** [comment]
@dangreenisrael, we're working through the issue, and I was hoping that you could take a look at your config.xml file for me, for a preference entry named "LoadUrlTimeoutValue".  I can set the message you mentioned in my own testing when the page initialization takes longer than that value, so I'm hoping there might be a short timeout value in your own configuration file.

If there is not an entry like that, the default timeout may be 20 seconds.  If the error is happening sooner than that, then I might going down the wrong trail, but if you see the error around the 20 second mark, perhaps adding a timeout preference would help.  For reference, the entry could look something like this:

`<preference name="LoadUrlTimeoutValue" value="30000"/>`

I'm going to keep looking through to see if I can find something else that would cause this. Any additional information you can provide would be great!

**Comment by dangreenisrael** [comment]
Awesome, I'm running the plugin from master and I added `<preference name="LoadUrlTimeoutValue" value="30000"/>`.  Everything seems to be working now, we'll do some more testing on different devices and let you know if it there is an issue again.
