### ISSUE TITLE
Calling logout now prevents branch.init callback ever firing again

### ISSUE THREAD

**Issue by Deminetix** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#2]
Calling `branch.init(key, null, callback)` - the callback is fired before and after using `branch.setIdentity(id, null)` but will never fire again after calling `branch.logout()`

**Comment by Deminetix** [comment]
This likely has something to do with commit 11240b9748de3911178c9fd818f93cdf17adb3f0 as we have been using this successfully for months.

**Comment by aaustin** [comment]
We're digging in @Deminetix

**Comment by vsubramanian** [comment]
:+1:

**Comment by vsubramanian** [comment]
Workaround I'm currently using for this issue is to call 

`branch.close` immediately followed by `branch.init` instead of doing `branch.logout`

**Comment by aaustin** [comment]
We're super short staffed right now - I'm hoping that we can get this resolved in the next couple days. I'm really sorry for the delay guys

**Comment by Kirkkt** [comment]
@Deminetix 

Sorry for the the late response, but web SDK v1.6.11 fixed this bug :)

Feel free to re-open it if the issue remains.
