### ISSUE TITLE
Compilation error on Android after "Add support for App Links" commit 

### ISSUE THREAD

**Issue by yossale** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#32]
After the "Add support for App Links" commit (81a201a4946982693a224afe1117acfb17408cea), building on Android fails due to:
```
private void readAndStripParam(Activity activity) {
	                               ^
  symbol:   class Activity
  location: class BranchDevice
/platforms/android/src/io/branch/BranchDevice.java:68: error: cannot find symbol
				Bundle bundle = activity.getIntent().getExtras();
				^
  symbol:   class Bundle
  location: class BranchDevice
/platforms/android/src/io/branch/BranchDevice.java:69: error: cannot find symbol
				Set<String> extraKeys = bundle.keySet();
				^
  symbol:   class Set
  location: class BranchDevice
```

**Comment by aaustin** [comment]
@yossale This is completely my fault. I committed and synced with master this weekend while adding support for App Links but it left off a lot of the changes I had made. Can you please grab the latest? I just pushed the rest of them.

**Comment by aaustin** [comment]
@yossale We just did a full release of 1.8.0 https://www.npmjs.com/package/branch-cordova-sdk

**Comment by yossale** [comment]
Cool, thanks!
