### ISSUE TITLE
Wrong repo in instructions?

### ISSUE THREAD

**Issue by dangreenisrael** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#34]
When trying to run `cordova plugin add https://github.com/BranchMetrics/Web-SDK.git`

I get 

`Error: ENOENT, no such file or directory ....`

The solution is to instead run 

` cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git`

Was this done on purpose?  Am I doing something wrong?

**Comment by aaustin** [comment]
Ack - @dangreenisrael I'm so sorry about this. That documentation is automatically generated and it was done incorrectly. I've just manually fixed that reference in the docs.

**Comment by aaustin** [comment]
Super sorry about this - we're revamping this repository now and will clean up a lot of this kind of mess.
