### ISSUE TITLE
iOS SSL Error

### ISSUE THREAD

**Issue by dangreenisrael** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#36]
I'm getting this error `Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. ---- https://api.branch.io/v1/close ` When my cordova app (iOS) comes out of paused state.

**Comment by aaustin** [comment]
@dangreenisrael There was some documentation somewhere that I read about an issue we have with cross-site security policies for automatic calls like that. I'll keep digging but does this ring a bell for you?

**Comment by dangreenisrael** [comment]
My app seems to be working fine for now.

I think I'm just going to ignore the error.

Definitely rings a bell, just thought I'd let you guys know about the error

**Comment by aaustin** [comment]
Ah - found this. Can you add the following to `res/xml/cordova.xml`:
```<access origin="https://api.branch.io" subdomains="true" />```

**Comment by aaustin** [comment]
Let me know if that works and I'll update it to the docs

**Comment by dangreenisrael** [comment]
Epic.

I put it in `config.xml ` and it worked.

Weird, because already had `<access origin="*" />` in there
