### ISSUE TITLE
Data in the init callback is returned as String

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#4]
We should return a nice JSON, not an ugly string

**Comment by dmitrig01** [comment]
we can't do this for backwards-compatibility. we return data_parsed as well, which is nice json

**Comment by aaustin** [comment]
I believe data_parsed is actually a string. Is that not the case? I'd recommend adding a new, basic data return which is the JSON.

**Comment by dmitrig01** [comment]
no. data is a string, data_parsed is an object

what do you mean by "adding a new, basic data return which is the JSON"

**Comment by aaustin** [comment]
if that's the case, no need.
