### ISSUE TITLE
iOS universal_link_url is not reset to nil after consumed

### ISSUE THREAD

**Issue by boxfish** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#41]
1. When clicking on a universal link to open the app, the `universal_link_url` is stored in cordova-src/ios/BNCDevice.m.
2. Then press the Home button and click on the app icon to open the app (which is NOT a universal link click).
3. Because the universal_link_url was not reset to nil, the same data from Step 1 got fetched inside `getOpenData`.

Note: the Android version is correctly resetting the values after consumed in `getOpenData` e.g. [this line](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/cordova-src/android/BranchDevice.java#L247)

**Comment by aaustin** [comment]
Thanks for the fix @boxfish
