### ISSUE TITLE
Push Version 2.0 to npm

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#45]
I'd like to use version 2.0 in my app.  I'm currently pulling from npm though.  Any idea when 2.0 will be published to npm for production use?

**Comment by aaustin** [comment]
Incoming today!

**Comment by gabaum10** [comment]
Excellent!  Thanks for the speedy update.

**Comment by aaustin** [comment]
Done and done!

**Comment by gabaum10** [comment]
I'll verify this is fixed with 2.0 and open it again if it is not.  Thanks for the hard work!
