### ISSUE TITLE
iOS cordova build fails with error: Branch/Branch.h not found

### ISSUE THREAD

**Issue by alrooney** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#48]
The android build works correctly, but the ios build returns the following error during the build:

CompileC build/Adored.build/Debug-iphonesimulator/Adored.build/Objects-normal/i386/BranchSDK.o Adored/Plugins/io.branch.sdk/BranchSDK.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/alec/.rvm/gems/ruby-2.2.4/bin:/Users/alec/.rvm/gems/ruby-2.2.4@global/bin:/Users/alec/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alec/.rvm/bin:/Users/alec/Library/Android/sdk/platform-tools:/Users/alec/Library/Android/sdk/tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=364 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/x4/tgy478h91pq8sf3h3_93bly00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Adored-generated-files.hmap -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Adored-own-target-headers.hmap -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Adored-all-target-headers.hmap -iquote /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Adored-project-headers.hmap -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/emulator/include -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/emulator/usr/local/lib/include -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/UninstalledProducts/include -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/emulator -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/DerivedSources/i386 -I/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/DerivedSources -F/Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/emulator -FAdored/Plugins/io.branch.sdk -include /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/sharedpch/Adored-Prefix-fadfkttyfyggspahrxbdtpvzcege/Adored-Prefix.pch -MMD -MT dependencies -MF /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Objects-normal/i386/BranchSDK.d --serialize-diagnostics /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Objects-normal/i386/BranchSDK.dia -c /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/Adored/Plugins/io.branch.sdk/BranchSDK.m -o /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/build/Adored.build/Debug-iphonesimulator/Adored.build/Objects-normal/i386/BranchSDK.o
In file included from /Users/alec/Developer/adored/adored-ember/cordova/platforms/ios/Adored/Plugins/io.branch.sdk/BranchSDK.m:8:
Adored/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
#import <Branch/Branch.h>
        ^
1 error generated.

** BUILD FAILED **

Looking at the xcode project the Branch.framework exists but it doesn't have a Headers directory like other frameworks.  Looking at it on the file system, however, it seems to be structured correctly like other frameworks.

**Comment by ZackMattor** [comment]
@alrooney This has been fixed in master, right?

**Comment by alrooney** [comment]
Yep.  Just confirmed that this is fixed in master.  Closing issue.

**Comment by akhudairyOP** [comment]
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/18
