### ISSUE TITLE
Plugin does not work by default.

### ISSUE THREAD

**Issue by ZackMattor** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#49]
You should not have to setDebug to have the plugin function. It should default to false, and have an opt in for debug. Having it fail silently isn't the best option IMO. And if this is really what you guys want it should really be called out in the docs. I can submit a PR for this after lunch if you guys want.

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/www/branch.js#L52-L71

**Comment by aaustin** [comment]
That's pretty dumb. I apologize. If you can fix it, it'd be much appreciated. Or I can toss it over to our contractors.

**Comment by ZackMattor** [comment]
Do you agree that it should default to debugMode being off? I can quickly make that change.

**Comment by jestoniyap** [comment]
There was a miscommunication on our end. The requirement for setDebug was supposed to be for the testbed app not for the actual plugin itself. We apologize for our mistake. I have removed the condition and execute the initSession once it is called.

**Comment by jestoniyap** [comment]
@ZackMattor Please close if this was resolved. Thanks.
