### ISSUE TITLE
iOS vs Android - DeepLinkHandler differences

### ISSUE THREAD

**Issue by ZackMattor** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#52]
There is an annoying difference in the DeepLinkHandler in iOS vs Android... iOS escapes the string passed so it doesn't come out as an object in javascript (you have to do `JSON.parse(data.data);`) and in Android it comes out as an object (as i think it should be) and it's not namespaced under a `.data` object.

`Android`
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/android/io/branch/BranchSDK.java#L673

`iOS`
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/ios/BranchSDK.m#L101

**Comment by jestoniyap** [comment]
Hello @ZackMattor, I removed the data namespace so it's the same with Android now. Pull request is currently pending. Thank you for the report.

**Comment by aaustin** [comment]
All set here. I'll deploy to NPM later tonight.

**Comment by ZackMattor** [comment]
@aaustin did you test to make sure that it doesn't escape that string? (as it was before)

**Comment by aaustin** [comment]
@ZackMattor Sorry - what do you mean escaping the string? You're saying the stringified version is corrupted? https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/55/files

**Comment by ZackMattor** [comment]
@aaustin see: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/57
