### ISSUE TITLE
contentMetaData doesn't seem to be appearing in the data when the user clicks the link

### ISSUE THREAD

**Issue by tkuben** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#54]
Hi, 

I created the Branch Universal Object using the following params: 

```
var universalObjParams = {canonicalIdentifier: 'identifier',
									  title: 'title',
									  contentDescription: '',
									  contentImageUrl: '',
									  contentIndexingMode: 'public', 
									  contentMetadata: {testData: 'some test data'}};
```

However, when the user clicks on the link based on this universal object, the data that gets into DeepLinkHandler does not contain the metaData "testData". How can I add additional data sets to a tracking link?

Based on the code base, it doesn't seem like there is anything being done with the contentMetaData: 

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/android/io/branch/BranchSDK.java#L377

Thoughts? 

TJ

**Comment by tkuben** [comment]
Hi, 

I believe in: 
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/android/io/branch/BranchSDK.java#L377

You should probably add a call to: 

https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/src/io/branch/indexing/BranchUniversalObject.java#L173

Attached File: [contentMetaDataFixPatch.diff.txt](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/files/156270/contentMetaDataFixPatch.diff.txt)

Please see the attached patch file which fixes the issue for me. The link generated using the compiled code had the contentMetaData when the user clicked and returned to the app. 

Cheers, 
TJ

**Comment by tkuben** [comment]
Please make the appropriate fix to the ios codebase as well.

**Comment by aaustin** [comment]
Hi @tkuben - I've just merged this to master and will do a deploy to NPM later today.

**Comment by tkuben** [comment]
Hi @aaustin 

Does the ios side of the SDK need a similar fix? I just opened a new issue for the IOS: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/62. The data does not seem to be coming through when someone clicks on an ios device. 

Thanks, 
TJ
