### ISSUE TITLE
iOS - "SyntaxError: Unexpected identifier 'Error'. Expected ')' to end a argument list."

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#60]
I'm getting this error when I try to go into offline mode in my app.  As best I can tell it is caused by this plugin.  If I remove it from my config, everything works correctly.  

Unfortunately, it's not giving me any stack trace so I really have no way of debugging this.  

My steps to reproduce are:
- Install
- Start the app up.  Wait a minute for everything to initialize
- Go into airplane mode to fire the cordova offline handlers.
- Observe the error in the safari tools

Now I have no idea why it would be throwing a syntax error there and not when it tried to load the script into the view.  For the record, this is NOT happening on Android.

**Comment by gabaum10** [comment]
If you start the app up with no connection, it throws this error and just sits on the splash screen.  You can't even get into the app. 

I built in handlers in the initialization sequence to not do the branch handlers if there is no connection, so it's something internal to the plugin that's executing when the connection is lost.

**Comment by gabaum10** [comment]
So the app not starting with no connection I mentioned above was actually because of a bug in my error processing code and you can disregard that, go figure.  But his error is still happening.  I just added a condition to ignore this specific error for the time being so I can still use the plugin.

**Comment by aaustin** [comment]
@gabaum10 I've filed this internally and we will hopefully hear something back in the next 10-12 hours. Sorry for the inconvenience.

**Comment by renesansz** [comment]
Hello @gabaum10,

It seems the iOS gets an error upon calling the `DeepLinkHandler` method from iOS to Javascript,
For some reason the response should be in form of a JSON string instead of string.

I've submitted my [pull request](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/65) and hopefully this will fix the error.

**Comment by jestoniyap** [comment]
@gabaum10 Please check if the issue was fixed then you can close this ticket. Thanks.
