### ISSUE TITLE
Phonegap incorrectly throwing error if encoded id not added

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#61]
See terminal command and error.

![error](https://cloud.githubusercontent.com/assets/1332632/13649094/bcaeb9ae-e5f0-11e5-8acc-4368fdcad9f6.PNG)

**Comment by renesansz** [comment]
Hey @aaustin,
I can't replicate the issue it seems the plugin can be install even without `ENCODED_ID` parameter.
(See screenshot)

![sc](http://prntscr.com/adas1l)

I've checked the command and it seems it's correct.
Is this issue coming from the latest commit for master?

**Comment by aaustin** [comment]
Interesting. Let me call out the partner that wrote in. Thanks for checking!!

**Comment by aaustin** [comment]
@renesansz I'm going to close this as the partner is unresponsive.
