### ISSUE TITLE
On ios, when someone clicks a link that was generated using an SDK that has contentMetadata, the click does not contain the custom data

### ISSUE THREAD

**Issue by tkuben** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#62]
Hi, 

I create the Universal Branch Object using the following: 

```
{canonicalIdentifier: 'someCan',
  title: 'Title',
  contentDescription: '',
  contentImageUrl: '',
  contentIndexingMode: 'private', 
  contentMetadata: {testData: 'Ssome Test Data'}};
```

and then generate a link using that object. I successfully receive the link from the call and am able to see the MetaData in my branch dashboard. However, on ios, when someone clicks the link, it opens the app however in the function: DeepLinkHandler, the data does not contain the meta information. This works flawlessly on android. 

This is a critical blocker for us as we are not able to deep link on the ios using custom data. Can someone please help!

Cheers, 
TJ

**Comment by jestoniyap** [comment]
@tkuben we are looking at the issue at the moment. We will update you once we have fixed the issue. Thank you.

**Comment by aaustin** [comment]
@tkuben This has been resolved - please try master or NPM 2.0.3

**Comment by tkuben** [comment]
Hi @aaustin 

I pulled the latest master and unfortunately having issues with the android build now :(
```

com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;


	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)


	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)

	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)

	at com.android.dx.command.dexer.Main.run(Main.java:277)


	at com.android.dx.command.dexer.Main.main(Main.java:245)


	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

```

Can we also please remove the autoVerify=true from the manifest? 

Cheers, 
TJ

**Comment by aaustin** [comment]
@renesansz Can you remove autoVerify=true from the manifest again?

**Comment by renesansz** [comment]
Hey @aaustin,
Just have checked the source code, the `autoVerify` was removed from the manifest already.

**Comment by tkuben** [comment]
Hi @renesansz @aaustin 

It seems the autoVerify is being injected into the Manifest from this line of code: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/hooks/lib/android/manifestWriter.js#L276

Cheers, 
TJ

**Comment by harshabonthu** [comment]
`autoVerify=true` is needed to enable automatic link handling verification for your app to support app links. Yes it is added from the plugin hooks along with intent-filter.

@tkuben  Check in your Android projects `libs` folder if you see branch.jar file which was being added from previous version of plugin. 

Ideal solution would be to reset cordova project i.e running below commands. This would recreate android project and clears any conflict from old plugin code. 

```

-  cordova plugin rm io.branch.sdk
-  cordova platform rm android
-  cordova platform add android
-  cordova build
-  cordova plugin add branch-cordova-sdk --save
-  cordova build

```

**Comment by renesansz** [comment]
Hello @tkuben ,
Please let us know if @harshabonthu 's solution works or not.

Thanks

**Comment by tkuben** [comment]
Hi @renesansz, 

It is still an issue unfortunately. Please see the comment on github: 

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/68

Your help in solving this matter would be much appreciated. I believe it has to do with conflicting libraries between the facebook plugin and branch. In particular it probably has something to do with: com.android.support:support-annotations:22.2.0 &  FacebookLib/libs/android-support-v4.jar

Any thoughts? 

Cheers, 
TJ

**Comment by renesansz** [comment]
I see,
Could you list down the plugins that you think that it might have a conflict with?
I'll try to replicate your issue and see through the problems upon using the plugin.

Thanks

**Comment by renesansz** [comment]
Hello @tkuben ,
Please see my response in #68, I hope this would resolve the issue.

Thanks

**Comment by renesansz** [comment]
Duplicate issue,
please see issue #68 instead.
