### ISSUE TITLE
iOS9 - Tries to hit fallback link every time from Safari (Chrome works fine)

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#64]
This may be a configuration problem on my end, but I can't be sure, especially with all the iOS issues I've run into over the past few weeks using branch.  In iOS9 the plugin seems to try and install the app every single time.  I can't seem to isolate which side it's coming from; the mapping on the branch side or something with the plugin.  

I've got everything set up in my config file for universal links since custom URLs are no longer supported in iOS9:

```
    <!-- Branch.io universal links -->
    <gap:plugin name="branch-cordova-sdk" source="npm">
        <param name="BRANCH_LIVE_KEY" value="@BRANCH_LIVE_KEY@" />
        <param name="URI_SCHEME" value="@URL_SCHEME@" />
    </gap:plugin>
    <gap:plugin name="cordova-universal-links-plugin" source="npm" />
    <universal-links>
        <ios-team-id value="@TEAM_ID@" />
        <host name="bnc.lt"></host>
    </universal-links>
```

The URL_SCHEME matches what I have configured in the branch.io dashboard.  The links are working correctly in iOS8 and below.  There are no errors.  

Also, the same setup is working on Android perfectly.  This might be a setup issue but since the plugin seems to be working right on Android so I thought it might be the plugin.

**Comment by gabaum10** [comment]
Also, to clarify a little more, my branch.io configuration is linking to anot ipa file hosted by phonegap build after it finishes building it.  This is just for development purposes.

Somehow the plugin is not detecting the app is already installed on the device and trying to install it again.

**Comment by gabaum10** [comment]
Wow, what's even more insane is this behavior only seems to be happening if I try to hit my target URL in safari.  If I use Chrome, the behaviors work as expected.  That's really weird.  

Also, sorry I haven't been able to contribute much more.

**Comment by aaustin** [comment]
Hey @gabaum10 - This seems like an Universal Links config issue, like where Team ID on our dash mismatches what you entered in the plugin.

Did you run through this troubleshooting guide on our site? https://dev.branch.io/getting-started/universal-app-links/support/cordova/#troubleshooting-universal-links

**Comment by gabaum10** [comment]
Oh, you're probably right.  I didn't even see those docs when I was getting things set up.  Sorry about that.  It's bizarre that chrome works correctly.

**Comment by zanemcca** [comment]
I am currently having this problem.
What did you do to fix your problem @gabaum10?

**Comment by gabaum10** [comment]
I didn't.  I was using phonegap build and they don't support the necessary hooks to generate the entitlements file using the branch plugin.  So I gave up deep links on ios for now.  It turns out all my config were right, PGB just won't work.

We have an internal project to get Cordova set up in our dev environment so I'll just implement the deep links once we do that.

**Comment by washowasho** [comment]
@gabaum10 Still the case? I'm seeing the same exact thing.

**Comment by gabaum10** [comment]
@washowasho is what still the case?  We switched over to in house cordova and dropped PGB and were able to get branch to work.  Although in the case of iOS we needed to use the [https://dev.branch.io/other/smart-banner/guide/](Branch Smart Banner) to get the deep link to work correctly.  It's an extra click but something we were comfortable with until we go native.

**Comment by washowasho** [comment]
@gbaum10 yeah, I was seeing if PGB still caused this issue. I confirmed that it does and I ended up switching to native Cordova as well.  Thanks for the response.
