### ISSUE TITLE
iOS - Universal links not configuring correctly

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#78]
So I've looked everywhere and done everything I can do.  As best I can tell, this plugin isn't configuring the necessary entitlements in the packaged IPA file. 

I used this [web service](https://limitless-sierra-4673.herokuapp.com/) to test the bnc.lt apple-app-site-association file to make sure my universal links are configured correctly on the branch side of things.  I was able to see the app I am looking for and it looks configured correctly.  

Then I uploaded my test IPA file that was generated with this plugin.  It's telling me `Must be able to find entitlements (looking in VeociDev/Payload/VeociDev.app/archived-expanded-entitlements.xcent)`.  

I have the necessary Associated Domains configuration set up for this app ID in the apple developer portal.  This is what my plugin configuation looks like in the config.xml file for the build, with the appropriate flags filled in:

```
   <!-- Branch.io universal links -->
    <plugin name="branch-cordova-sdk" source="npm">
        <param name="BRANCH_KEY" value="@BRANCH_LIVE_KEY@" />
        <param name="URI_SCHEME" value="@URL_SCHEME@" />
    </plugin>
    <branch-config>
        <ios-team-id value="@TEAM_ID@" />
        <android-prefix value="/X9Ug" />
        <host name="bnc.lt" scheme="https" />
    </branch-config>
```

Am I doing something wrong, or is there a bug here somewhere?

**Comment by gabaum10** [comment]
Here is a screenshot of the result:

![univerallinktest](https://cloud.githubusercontent.com/assets/1561245/13953248/5c5ce1d6-f011-11e5-88eb-7480d2401030.PNG)

**Comment by gabaum10** [comment]
I may have asked this before, but does the plugin use Cordova hooks to setup the universal links config stuff?  That may be why this is failing.  Phonegap Build doesn't support hooks so I may be out of luck.

**Comment by renesansz** [comment]
@gabaum10 , yes, there are hooks being executed upon building the plugin. I'm sorry to hear that, I think they don't have the intention on implementing it soon.

**Comment by gabaum10** [comment]
Crap, @renesansz or anyone else, are you aware of any cross platform tools that would support hooks?  The problem is I don't have access to a mac to do iOS builds.  I've tried Phonegap build and Intel XDK and neither of them support hooks.

**Comment by gabaum10** [comment]
Well, I guess this isn't really a problem with this plugin but rather shortcomings in PGB.  Here is a similar plugin here:
