### ISSUE TITLE
Bunch of iOS (+1 java) plugin issues that still need to be addressed

### ISSUE THREAD

**Issue by pragunvohra** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#80]
BranchSDK.m - unresolved issues:
  1. Only a single BranchUniversalObject on the class (self.branchUniversalObj), which means, as with Java, multiple calls to CreateBranchUniversalObject will clobber prior calls to that method.
  2. ~~setDebug does not resolve a promise~~ https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/86
  3. Memory leaks (e.g. [NSString alloc] will need to be released)
  4. userCompletedAction still needs a way to resolve a promise depending on if the http call succeeded / via a listener; it returns too early right now

I did not (really) look at the following methods, but if I found anything from a cursory glance that I have not addressed, it's listed here (I also didn't check to ensure that we were returning the proper objects instead of just JSON strings, and whether those objects were consistent with the Java implementation):
  1. getAutoInstance
  2. registerDeepLinkController
  3. redeemRewards
  4. initWithCanonicalIdentifier
  5. initWithTitle
  6. addMetadata - does not resolve a promise 
  7. registerView  - does not resolve a promise
  8. showShareSheet - does not resolve a promise
  9. listOnSpotlight

BranchSDK.java - unresolved issues: 
  1. ~~setDebug does not resolve a promise~~
  2. userCompletedAction still needs a way to resolve a promise depending on if the http call succeeded / via a listener; it returns too early right now

**Comment by renesansz** [comment]
@pragunvohra ,
Thanks for the report, however I think I'll be needing my colleague here to fix the issues for iOS.

In regards to userCompletedAction (Android). I think this should be fixed first on the Android SDK itself, since there is no other way to resolve the promise being returned to early.
I'll consult first to the other developers for this plugin, if they have solution for this issue.

**Comment by pragunvohra** [comment]
No problem.
Re: userCompletedAction -- that's correct; userCompletedAction will need a new overload on both the Android & iOS SDKs with a callback handler.

**Comment by jestoniyap** [comment]
@pragunvohra This is currently in progress. We'll let you know once the changes are available.

**Comment by aaustin** [comment]
@pragunvohra We're ready to merge in #92. Take a gander if you get a chance. Thanks!

**Comment by pragunvohra** [comment]
@aaustin - just did, sorry I hadn't seen @jestoniyap's comment from last week.
Overall, it looks better. I would not replace boolean return values with strings though, and I think there are some possible memory leaks.
I left more detailed comments in the PR.

**Comment by aaustin** [comment]
We're all set here, so I'm closing this issue out. Thanks for your help!
