### ISSUE TITLE
ios build fails with error Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by vinaydahiwale** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#83]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by aaustin** [comment]
Sorry about this: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/85
