### ISSUE TITLE
Android build fails: Cannot find symbol this.setIntent(intent);

### ISSUE THREAD

**Issue by Morathil** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#84]
When i'm trying to build my project with the latest version i'm getting the follwing error:
`:compileArmv7DebugJavaWithJavac/.../platforms/android/src/io/branch/BranchSDK.java:62: error: cannot find symbol
        this.setIntent(intent);
            ^
  symbol: method setIntent(Intent)
`
Maybe this issue is connected with #82 ?

**Comment by p1ng** [comment]
+1

**Comment by aaustin** [comment]
Sorry team: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/85

**Comment by p1ng** [comment]
#85 fixed this and the android resume issue.  Great work!

**Comment by aaustin** [comment]
Phew! Sorry about the delay in resolution :(
