### ISSUE TITLE
Should we call setDebug before or after initSession? Clarify in docs

### ISSUE THREAD

**Issue by pragunvohra** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#87]
Docs should be updated here, but I'm not sure which one it should be --

iOS docs state that setDebug should be called before initSession: 
https://dev.branch.io/getting-started/integration-testing/guide/ios/#use-debug-mode-to-simulate-fresh-installs

branch.js states it should be called after initSession:
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/www/branch.js#L66

**Comment by renesansz** [comment]
@pragunvohra sorry for the typo, set debug must be called first before initSession.

**Comment by aaustin** [comment]
Fixed on master https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/commit/83c87dcdf1e50a725cb31f33dff27c41ab58a7d6
