### ISSUE TITLE
Need to be able to pass nonbranch links

### ISSUE THREAD

**Issue by jstoup111** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#89]
This seems strange that I'm unable to do this.

my_scheme://reset_password?token=asdfawefawef

I can click the link, it opens my app, but I get no information about the link at all. This is a pretty big issue as I don't want to have to create a Branch link on the server side for every link I need to send to my app. I'd also hate to create a dependency for every event in my app when I have all the data I need right there. Is there a way to utilize both Branch and retrieve the URL from the link clicked above? 

This is a critical issue for me.

**Comment by Sarkar** [comment]
@jstoup111 when creating a link, you should specify the key "$ios_deeplink_path" or "$android_deeplink_path", with the value of "reset_password?token=asdfawefawef" - that way, we'll take your registered scheme in your Branch dashboard, and append that value.

give that a go - it'll open your app + pass along that URI scheme for you!

**Comment by jstoup111** [comment]
Hi sorry I wasn't clear. I do not want a Branch dependency serverside. I do not want a Branch Link in every case that I need to open my app. Please support both, or pass the URL that opened the app in the object.

My usecase is to not use at all in this specific case, and use Branch for cases that are social in nature.

**Comment by aaustin** [comment]
Hey @jstoup111 - I understand the issue. Sorry for the misfire. How are you expecting to receive your other URIs? How are we munching them in the process? This will help inform our fix. Thanks!

**Comment by jstoup111** [comment]
@aaustin Thanks for the response. What happens in the library now, is that an object is passed to `DeepLinkHandler` that contains the following. 

```{+is_first_session: false, +clicked_branch_link: false}```

If it's a branch link, the whole object is populated. I think the easiest and best solution is to have a `+refered_url` or `+opened_url` that passes the URL that opened the app. Then if it's a branch link, you'll have that link (or something similar) but if it's not a branch link, we can still handle that flow.

**Comment by jstoup111** [comment]
Just wanted to follow up on this with an expected fix? Need to plan this around with the release since this is a known bug that will affect people using our app (they won't be able to reset passwords, or navigate to any screens in the app without a branch link). This is definitely a big problem, but if you have an expected timeline for when this might be fixed, it would help us to relay information out to our users.

**Comment by jestoniyap** [comment]
@jstoup111 This is in progress. We will inform you once we have the fix. Thank you.

**Comment by danvine** [comment]
@jestoniyap more than happy to help test!

**Comment by BoboFraggins** [comment]
@jestoniyap Any ETA on the fix? It's burning us, too.

**Comment by jestoniyap** [comment]
@BoboFraggins @jstoup111 Created a pull request. Hopefully, it will be approved soon.

**Comment by jstoup111** [comment]
@jestoniyap Thanks for the update. Is this also an issue for Android? I saw only iOS changes there.

**Comment by jestoniyap** [comment]
@jstoup111 I'll have my colleague @renesansz check it out. We'll let you know when we have an update. Thanks.

**Comment by renesansz** [comment]
noted, will work on with the Android for this. 👍

**Comment by renesansz** [comment]
Submitted PR #111 for Android. Please check. Thanks

**Comment by jstoup111** [comment]
I'll be able to check it out this weekend. Thanks for the update :)

**Comment by jstoup111** [comment]
iOS appears to be working properly 👍 Not able to test Android at the moment unfortunately, so if anyone else can confirm that'd be great and I can close this out :)

**Comment by renesansz** [comment]
@jstoup111 ,
Confirmed that this is working as expected. 👍

**Comment by jstoup111** [comment]
Cool closing
