### ISSUE TITLE
Breaking PhoneGap Builds:  Malformed Plugin.xml

### ISSUE THREAD

**Issue by randallbpotter15** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#9]
Pull Request:  It's breaking builds with PhoneGap:
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/8

**Comment by Kirkkt** [comment]
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/8 is in. 

Many thanks!
