### ISSUE TITLE
logout method causing app crash

### ISSUE THREAD

**Issue by rklus16** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#95]
In iOS, after setting the user identity successfully, then I try to log the user out the app crashes and I get this log in the console.

```
2016-04-08 19:24:18.743 myApp[2100:433852] start logout
2016-04-08 19:24:18.744 myApp[2100:433852] start getInstance
2016-04-08 19:24:19.330 myApp[2100:433852] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb00000000010f7e5
2016-04-08 19:24:19.334 myApp[2100:433852] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb00000000010f7e5'
*** First throw call stack:
(0x1815cae38 0x180c2ff80 0x1815d1ccc 0x1815cec74 0x1814ccd1c 0x10018bb44 0x100194b2c 0x100182280 0x100645a7c 0x100645a3c 0x10064b4e4 0x181580dd8 0x18157ec40 0x1814a8d10 0x182d90088 0x18677df70 0x10002c658 0x1810468b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

xcode also displays this line in [BNCPreferenceHelper setUserIdentity:] as the issue.
> <+116> at BNCPreferenceHelper.m:293

**Comment by renesansz** [comment]
@rklus16 , Some I can't produce the issue you've reported.
Can you provide specific steps on how to replicate the error?
Also please provide the details of your setup (eg: `cordova version`, `plugin versions`, etc..)

**Comment by rklus16** [comment]
Cordova version: 6.1.1
iOS platform version: 4.1.1
Branch plugin version: 2.0.9

We have it setup that when a user logs into our system a user id is returned which we use for setIdentity method like so. 

```
user_id = 1111; // returned user id
Branch.setIdentity(user_id);
```
Once the user logs out we call the logout method. 
```
Branch.logout();
```

**Comment by rklus16** [comment]
Works for android.

For iOS, I'm using Xcode Version 7.3 (7D175). I don't know if that would be an issue though.

**Comment by rklus16** [comment]
I think I've figured out the issue. I was passing in the id as a json object. I thought on callback it was already stringified but I guess not. JSON.stringify seems to have fixed the issue.
