### ISSUE TITLE
Default text of showShareSheet

### ISSUE THREAD

**Issue by rklus16** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#97]
Is it possible to change the default text "Share link" in the showShareSheet?

![img_0017](https://cloud.githubusercontent.com/assets/3171887/14447963/13699edc-002a-11e6-90ee-24269121481c.jpg)

**Comment by rt2zz** [comment]
upon cursory inspection it looks like the fourth argument to `showShareSheet` will be set as the share text https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/ios/BranchSDK.m#L474

**Comment by rklus16** [comment]
looks like showShareSheet only take 2 args `showShareSheet(options, controlParameters)` so I'm not sure what the third and fourth arguments are. I tried this

`showShareSheet(options, controlParams, 'my example text');`

**Comment by rt2zz** [comment]
Ah true, it looks like www/branch.js is lacking support atm

**Comment by TheMarshal99** [comment]
Related: Android seems to be ignoring any call to showShareSheet with 4 arguments.

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/eb38b43138d1382c8cdfce1abd184d4e89d3dbce/src/android/io/branch/BranchSDK.java#L189

**Comment by renesansz** [comment]
Hey everyone,
Just have created a PR #99  to support customizing the share text.

**Comment by jestoniyap** [comment]
@rklus16 Please check if the latest version fixes the issue. Then we can close this thread. Thanks.

**Comment by rklus16** [comment]
Works! Thanks for doing that! 😃
